List<dynamic> trans_list = [
  {
    'id': 0,
    'title': "McDonalds",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/mcdonalds.png',
    'price_text': "\$12.99",
  },
  {
    'id': 1,
    'title': "Exchange from INR",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/exchange.png',
    'price_text': "\$401.98",
  },
  {
    'id': 2,
    'title': "H&M Clothing",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/clothing.png',
    'price_text': "\$129.99",
  },
  {
    'id': 3,
    'title': "Load Currency USD",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/loadcurrency.png',
    'price_text': "\$150",
  },
  {
    'id': 4,
    'title': "ATM Withdrawal",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/atm.png',
    'price_text': "\$40.00",
  },
  {
    'id': 5,
    'title': "Exchange from INR",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/exchange.png',
    'price_text': "\$401.98",
  },
  {
    'id': 6,
    'title': "H&M Clothing",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/clothing.png',
    'price_text': "\$129.99",
  },
  {
    'id': 7,
    'title': "Load Currency USD",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/loadcurrency.png',
    'price_text': "\$150",
  },
  {
    'id': 8,
    'title': "ATM Withdrawal",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/atm.png',
    'price_text': "\$40.00",
  },
  {
    'id': 9,
    'title': "Exchange from INR",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/exchange.png',
    'price_text': "\$401.98",
  },
  {
    'id': 10,
    'title': "McDonalds",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/mcdonalds.png',
    'price_text': "\$12.99",
  },
  {
    'id': 11,
    'title': "H&M Clothing",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/clothing.png',
    'price_text': "\$129.99",
  },
  {
    'id': 12,
    'title': "Load Currency USD",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/loadcurrency.png',
    'price_text': "\$150",
  },
  {
    'id': 12,
    'title': "ATM Withdrawal",
    'subtitle': "12:12 AM IST • Sep 2",
    'img_path': 'images/home/tab_1/atm.png',
    'price_text': "\$40.00",
  }
];
