import 'dart:convert';

import 'package:digitatravelmoney/data/models/post2.dart';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';

class Post2Repository {
  Future<List<Autogenerated>> fetchPosts() async {
    List<Autogenerated> posts = [];
    var dio = Dio();

    var response = await dio.get('https://jsonplaceholder.typicode.com/users');
    if (response.statusCode == 200) {
      var data = json.decode(response.data);
      data.map((post) => posts.add(Autogenerated.fromJson(post))).toList();
    }
    return posts;
  }
}
