// part of 'Post2_bloc.dart';

// import 'package:digitatravelmoney/data/models/post2.dart';
// import 'package:equatable/equatable.dart';

// abstract class Post2State extends Equatable {
//   const Post2State();
//   @override
//   List<Object> get props => [];
// }

// class InitialState extends Post2State {}

// class LoadingState extends Post2State {}A

// class LoadedState extends Post2State {}

// class FetchSuccess extends Post2State {
//   late List<Autogenerated> posts;
//   FetchSuccess({required this.posts});
// }

// class ErrorState extends Post2State {
//   late String message;
//   ErrorState({required this.message});
// }
